---
- name: Install required packages
  ansible.builtin.apt:
    name:
      - "ca-certificates"
      - "curl"
      - "gnupg"
    state: present
    update_cache: true

- name: Get docker keyrings
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Set docker keyrings permissions
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    state: file
    mode: a+r

- name: Add the repository to Apt sources
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Install latest package versions
  ansible.builtin.apt:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "docker-buildx-plugin"
      - "docker-compose-plugin"
    state: present
    update_cache: true
